"""empty message

Revision ID: 96edeef108c9
Revises: cc70b4f267f6
Create Date: 2024-11-04 23:55:11.764681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96edeef108c9'
down_revision: Union[str, None] = 'cc70b4f267f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    # ### end Alembic commands ###
