"""empty message

Revision ID: bf40f607c8c5
Revises: 3aad37a60866
Create Date: 2024-11-02 21:27:03.787744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf40f607c8c5'
down_revision: Union[str, None] = '3aad37a60866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_session_fingerprint_hash_key', 'user_session', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_session_fingerprint_hash_key', 'user_session', ['fingerprint_hash'])
    # ### end Alembic commands ###
